name: HW Analyse Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install psutil

    - name: Run analysis (modo texto)
      run: |
        python analise_hardware.py || echo "Gradio não roda em CI, mas HTML pode ser gerado"
